dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 16
  dataset_path: /path/to/data
  centering: sinkhorn_knopp
student:
  arch: vit_base
  img_size: [192, 224, 48]
  patch_size: [16, 16, 8]
  in_chans: 4
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 50
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 8
  layerwise_decay: 1.0
crops:
  global_crops_scale:
  - 0.48
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.16
  - 0.48
  global_crops_size: [192, 224, 48]
  # local_crops_size: [96, 112, 24]
  local_crops_size: [80, 96, 24]
  